CREATE USER 'uid1'@'%' IDENTIFIED BY '12345';
GRANT ALL PRIVILEGES ON dtbaza.* TO 'uid1'@'%';
FLUSH PRIVILEGES;

CREATE USER 'uid2'@'%' IDENTIFIED BY '12345';
GRANT ALL PRIVILEGES ON dtbaza.* TO 'uid2'@'%';
FLUSH PRIVILEGES;

CREATE USER 'uid3'@'%' IDENTIFIED BY '12345';
GRANT ALL PRIVILEGES ON dtbaza.* TO 'uid3'@'%';
FLUSH PRIVILEGES;
